version: 0.2

env:
  variables:
    IMAGE_TAG: latest
    REPOSITORY_URI: 977099019525.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app

phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo IMAGE_TAG=$IMAGE_TAG
      - echo REPOSITORY_URI=$REPOSITORY_URI
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - deployment.yaml
    - service.yaml

